### PR TITLE
New platforms

### PR DESCRIPTION
**Pull request by Himura2la**
I reverted the changes for CHIP and added Omega2 example. It doesn't have much input devices and I even was unable to make work 1wire and python GPIO lib. But I made a led-blinking example. There are four LEDs to blink ))

### CODE REVIEW

**Comment by Himura2la** [comment]
For GPIO support on CHIP, the https://github.com/xtacocorex/CHIP_IO is required

**Comment by Himura2la** [comment]
How do you write python-agnostic code??? It's a pain..

**Comment by vutenkov** [comment]
> How do you write python-agnostic code??? It's a pain..

I believe a simple for-loop will do just fine

`
RGB = {'R': '17', 'G': '16', 'B': '15'}

for _, pin in RGB.items():
    ...
`

Regarding the new example, while the led blinking is definitely a nice "hello world" when learning some new micro computer, here we are trying to show how to use this library to communicate with your web control panels. So how about you change the sample to blink LEDs from the UI? You could use our [MqttApi](https://github.com/cloud4rpi/cloud4rpi/blob/master/examples/mqtt_publish.py#L3)  to send/receive messages.

**Comment by Himura2la** [comment]
`for _, pin in RGB.items():` items is Python3. In Python2 it's iteritems ((

**Comment by Himura2la** [comment]
And also my code fully uses the cloud4rpi platform to control 4 onboard LEDS, three of which are on the GPIO bus

**Comment by vutenkov** [comment]
> for _, pin in RGB.items(): items is Python3. In Python2 it's iteritems ((

Are you sure? https://docs.python.org/2/library/stdtypes.html#dict.items

**Comment by Himura2la** [comment]
Oh, thank you, now I know more... For some reason I was sure 'items' is not backward compatible

**Comment by Himura2la** [comment]
Do you have an idea of what can we display as an output? I have found no CPU thermometer on this board

**Comment by vutenkov** [comment]
To blink a LED it's not necessary to display any output, but if you want, you could bind the same boolean variable you're using to control the device's pins to a chart or something.

``` 
from cloud4rpi import api_client

client = api_client.MqttApi('!!!YOUR_DEVICE_TOKEN!!!')
client.connect()
variables = [
    {'name': 'LED', 'type': 'bool', bind: led_control},
]
client.publish_config(variables)

# here should be your control loop
```
https://github.com/cloud4rpi/cloud4rpi/blob/master/examples/actuator.py#L24

**Comment by Himura2la** [comment]
The output of the resulting value is supported in my code. I was thinking about something like CPU load, but it seems pretty hard to implement on pure non-debian linux (openWRT-like). Maybe a number of running processes...

**Review by vutenkov — APPROVED** [review]

**Review by iBat — APPROVED** [review]

**Review by sky3d — APPROVED** [review]

**Pull request merged**
