### PR TITLE
Service install script rework

### PR DESCRIPTION
**Pull request by Himura2la**
I embed everything into a single file. Please carefully review it because my experience in bash-scripting is not great. 

- [x] Code Review
- [x] Test on SystemD
- [x] Test on System V
- [x] Merge
- [x] Update docs

### CODE REVIEW

**Review by sky3d — APPROVED** [review]
systemd tested ok

**Comment by Himura2la** [comment]
I'm going to rework it a little bit to avoid intermediate file. sed will output right into `$SYSTEMV_DIR`
In case the user has no root permissions, the file won't be created

**Comment by Himura2la** [comment]
```bash
$PYTHON_PATH $SCRIPT &> $LOGFILE & echo $!
```
this doesn't seen to work (systemv), the logfile is empty on my system.

**Comment by Himura2la** [comment]
This was caused by file operations buffering. I fixed this with the -u key of python

**Review by vutenkov — APPROVED** [review]

**Pull request merged**
