### PR TITLE
 service_install.sh as submodule

### PR DESCRIPTION
**Pull request by Himura2la**
We can use the `http://cloud4rpi.io/service_install.sh` URL to download the script with `wget`.
If anyone wants the script locally, he can clone with the `--recursive` flag or execute `git submodule update --init` afterwards

### CODE REVIEW

**Review by const314 — APPROVED** [review]

**Comment by Himura2la** [comment]
@vutenkov Can we merge this at least here?

**Comment by vutenkov** [comment]
Do we even need that script in this repo?

**Comment by Himura2la** [comment]
maybe no, but it was here inititally and it is a part of our service

**Comment by vutenkov** [comment]
I think we should remove it. Any thoughts @const314, @sky3d?

**Comment by Himura2la** [comment]
We discussed this with @sky3d, he says there's a public gist and it should be enough. OK then, closing.

**Pull request closed without merging**
